byte: word_ladder.byte

native: word_ladder.native

word_ladder.byte: word_ladder.ml
	corebuild -pkg core,ocamlgraph,extlib,batteries word_ladder.byte

word_ladder.native: word_ladder.ml
	corebuild -pkg core,ocamlgraph,extlib,batteries word_ladder.native
